from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from torch import nn

from .config import load_config, save_config
from .data import (
    ContextEncoder,
    LabelEncoder,
    assert_class_coverage,
    assert_disjoint,
    assert_group_disjoint,
    create_splits,
    load_manifest,
)
from .experiment import build_dataset_loader, fit_model
from .training.engine import predict_loader
from .training.metrics import compute_metrics
from .training.plots import (
    plot_confusion_matrix,
    plot_reliability_diagram,
    plot_training_history,
)
from .utils.io import file_sha256, write_json
from .utils.reproducibility import resolve_device, set_global_seed


def _predictions_frame(
    source_frame: pd.DataFrame,
    result,
    class_names: list[str],
) -> pd.DataFrame:
    rows = source_frame.loc[result.source_indices].copy()
    rows = rows.reset_index(drop=True)
    rows["target_index"] = result.targets
    rows["target_label"] = [class_names[index] for index in result.targets]
    predicted = result.probabilities.argmax(axis=1)
    rows["predicted_index"] = predicted
    rows["predicted_label"] = [class_names[index] for index in predicted]
    rows["confidence"] = result.probabilities.max(axis=1)
    for index, class_name in enumerate(class_names):
        rows[f"probability_{class_name}"] = result.probabilities[:, index]
    return rows.drop(columns=[column for column in ["_absolute_path"] if column in rows.columns])


def _write_split_assignments(source_frame: pd.DataFrame, splits, output_path: Path) -> None:
    assignments = source_frame[["image_path"]].copy()
    assignments["split_assignment"] = ""
    assignments.loc[splits.train, "split_assignment"] = "train"
    assignments.loc[splits.val, "split_assignment"] = "validation"
    assignments.loc[splits.test, "split_assignment"] = "test"
    for column in ["species", "device", "trap_color", "group_id"]:
        if column in source_frame.columns:
            assignments[column] = source_frame[column]
    assignments.to_csv(output_path, index=False)


def _subgroup_metrics(
    predictions: pd.DataFrame,
    probabilities: np.ndarray,
    class_names: list[str],
    context_columns: list[str],
) -> pd.DataFrame:
    records: list[dict] = []
    for column in context_columns:
        if column not in predictions.columns:
            continue
        for value, group in predictions.groupby(column, dropna=False):
            positions = group.index.to_numpy()
            metrics = compute_metrics(
                group["target_index"].to_numpy(), probabilities[positions], class_names
            )
            records.append(
                {
                    "context_column": column,
                    "context_value": str(value),
                    "n_images": len(group),
                    "accuracy": metrics["accuracy"],
                    "balanced_accuracy": metrics["balanced_accuracy"],
                    "macro_f1": metrics["macro_f1"],
                    "expected_calibration_error": metrics["expected_calibration_error"],
                }
            )
    return pd.DataFrame(records)


def _write_summary(
    output_dir: Path,
    config: dict,
    splits,
    fit_result,
    metrics: dict,
    evaluation_split: str,
    manifest_sha256: str,
) -> None:
    data_config = config["data"]
    lines = [
        "# Run summary",
        "",
        f"- Evaluation split: **{evaluation_split}**",
        f"- Manifest SHA-256: `{manifest_sha256}`",
        f"- Train images: **{len(splits.train)}**",
        f"- Validation images: **{len(splits.val)}**",
        f"- Test images: **{len(splits.test)}**",
        f"- Backbone: **{config['model']['backbone']}**",
        f"- Context used: **{config['model']['use_context']}**",
        f"- Context columns: **{', '.join(data_config.get('context_columns', []))}**",
        f"- Best epoch: **{fit_result.best_epoch}**",
        f"- Best validation macro-F1: **{fit_result.best_macro_f1:.4f}**",
        f"- Evaluation macro-F1: **{metrics['macro_f1']:.4f}**",
        f"- Evaluation balanced accuracy: **{metrics['balanced_accuracy']:.4f}**",
        f"- Expected calibration error: **{metrics['expected_calibration_error']:.4f}**",
        "",
        "These values are generated by the current dataset and configuration. Inspect the manifest, "
        "split design, predictions, and error cases before drawing biological conclusions.",
    ]
    (output_dir / "run_summary.md").write_text("\n".join(lines), encoding="utf-8")


def run(config_path: str | Path) -> dict:
    config = load_config(config_path)
    seed = int(config["seed"])
    set_global_seed(seed)
    output_dir = Path(config["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    save_config(config, output_dir / "config_resolved.yaml")
    manifest_sha256 = file_sha256(config["data"]["manifest"])

    frame = load_manifest(config["data"]["manifest"], config["data"]["image_root"])
    splits = create_splits(frame, config["data"], seed)
    assert_disjoint(splits)
    if bool(config["data"].get("enforce_group_disjoint", True)):
        assert_group_disjoint(frame, splits, config["data"].get("group_column"))
    assert_class_coverage(
        frame,
        splits,
        str(config["data"].get("target_column", "species")),
        require_test=True,
    )
    _write_split_assignments(frame, splits, output_dir / "split_assignments.csv")
    if len(splits.train) == 0 or len(splits.val) == 0:
        raise ValueError("Training and validation splits must both be non-empty.")

    target_column = str(config["data"].get("target_column", "species"))
    context_columns = list(config["data"].get("context_columns", []))
    train_frame = frame.loc[splits.train]
    val_frame = frame.loc[splits.val]
    test_frame = frame.loc[splits.test] if len(splits.test) else val_frame
    evaluation_split = "test" if len(splits.test) else "validation"

    label_encoder = LabelEncoder.fit(train_frame[target_column])
    context_encoder = ContextEncoder.fit(train_frame, context_columns)

    train_bundle = build_dataset_loader(
        train_frame, config, label_encoder, context_encoder, train=True
    )
    val_bundle = build_dataset_loader(
        val_frame, config, label_encoder, context_encoder, train=False
    )
    test_bundle = build_dataset_loader(
        test_frame, config, label_encoder, context_encoder, train=False
    )

    device = resolve_device(str(config["training"].get("device", "auto")))
    fit_result = fit_model(
        train_bundle,
        val_bundle,
        config,
        label_encoder,
        context_encoder,
        device,
        checkpoint_path=output_dir / "best.pt",
    )
    fit_result.history.to_csv(output_dir / "history.csv", index=False)
    plot_training_history(fit_result.history, output_dir / "training_history.png")

    criterion = nn.CrossEntropyLoss()
    evaluation = predict_loader(fit_result.model, test_bundle.loader, criterion, device)
    class_names = [
        label_encoder.idx_to_class[index] for index in range(len(label_encoder.class_to_idx))
    ]
    metrics = compute_metrics(evaluation.targets, evaluation.probabilities, class_names)
    metrics["evaluation_split"] = evaluation_split
    metrics["best_epoch"] = fit_result.best_epoch
    metrics["best_validation_macro_f1"] = fit_result.best_macro_f1
    metrics["manifest_sha256"] = manifest_sha256
    write_json(metrics, output_dir / "metrics.json")

    predictions = _predictions_frame(frame, evaluation, class_names)
    predictions.to_csv(output_dir / "predictions.csv", index=False)
    subgroup = _subgroup_metrics(
        predictions,
        evaluation.probabilities,
        class_names,
        context_columns,
    )
    subgroup.to_csv(output_dir / "subgroup_metrics.csv", index=False)
    matrix = np.asarray(metrics["confusion_matrix"])
    plot_confusion_matrix(matrix, class_names, output_dir / "confusion_matrix.png")
    plot_reliability_diagram(
        evaluation.targets,
        evaluation.probabilities,
        output_dir / "reliability_diagram.png",
    )
    _write_summary(
        output_dir,
        config,
        splits,
        fit_result,
        metrics,
        evaluation_split,
        manifest_sha256,
    )
    return metrics


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Train and evaluate an insect classifier.")
    parser.add_argument("--config", required=True, help="Path to experiment YAML configuration.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    metrics = run(args.config)
    print(
        f"Completed. Macro-F1={metrics['macro_f1']:.4f}; "
        f"balanced accuracy={metrics['balanced_accuracy']:.4f}"
    )


if __name__ == "__main__":
    main()
